In [2]:

import numpy as np
# Creating a 1D NumPy array
heights = np.array([150, 160, 170, 180, 190])
print(heights)

[150 160 170 180 190]


In [3]:
print(heights[0]) 
print(heights[2])
print(heights[-1])

150
170
190


In [4]:
print(heights[1:4])
print(heights[:3])
print(heights[2:])
print(heights[:])

[160 170 180]
[150 160 170]
[170 180 190]
[150 160 170 180 190]


In [5]:
arr_2d = np.array([ [150, 50],
                    [160, 60],
                    [170, 65],
                    [180, 80],
                    [190, 90]])
print(arr_2d)

[[150  50]
 [160  60]
 [170  65]
 [180  80]
 [190  90]]


In [6]:
print(arr_2d[0, 0]) 
print(arr_2d[1, 1])
print(arr_2d[4, 1])  # 4 setir 1 sutun 

150
60
90


In [7]:
print(arr_2d[1:4, 0])  # 1 - 4 setir ,  0 sutun
print(arr_2d[:,   1])  
print(arr_2d[2:, :])

[160 170 180]
[50 60 65 80 90]
[[170  65]
 [180  80]
 [190  90]]


In [8]:
heights = arr_2d[:, 0]
tall_people = heights[heights > 170]
print(tall_people)

[180 190]


In [9]:
selected_rows = arr_2d[[0, 2, 4], :]
print(selected_rows)

[[150  50]
 [170  65]
 [190  90]]


In [10]:
heights = np.array([150, 160, 170, 180, 190])
weights = np.array([50, 60, 65, 80, 90])

print("Heights:", heights)
print("Weights:", weights)

Heights: [150 160 170 180 190]
Weights: [50 60 65 80 90]


In [11]:
heights_in_meters = heights / 100
print("Heights in meters:", heights_in_meters)

Heights in meters: [1.5 1.6 1.7 1.8 1.9]


In [12]:
scaled_weights = weights * 2
print("Scaled Weights (multiplied by 2):", scaled_weights)

Scaled Weights (multiplied by 2): [100 120 130 160 180]


In [13]:
combined = heights * weights
print("Combined:", combined)

Combined: [ 7500  9600 11050 14400 17100]


In [14]:
mean_height = np.mean(heights)
mean_weight = np.mean(weights)
print("Mean Height:", mean_height)
print("Mean Weight:", mean_weight)

Mean Height: 170.0
Mean Weight: 69.0


In [15]:
std_height = np.std(heights)
std_weight = np.std(weights)
print("Standard Deviation of Heights:", std_height)
print("Standard Deviation of Weights:", std_weight)

Standard Deviation of Heights: 14.142135623730951
Standard Deviation of Weights: 14.2828568570857


In [16]:
var_height = np.var(heights)
var_weight = np.var(weights)
print("Variance of Heights:", var_height)
print("Variance of Weights:", var_weight)

Variance of Heights: 200.0
Variance of Weights: 204.0


In [17]:
median_height = np.median(heights)
median_weight = np.median(weights)
print("Median Height:", median_height)
print("Median Weight:", median_weight)

Median Height: 170.0
Median Weight: 65.0


In [18]:
min_height = np.min(heights)
max_height = np.max(heights)
min_weight = np.min(weights)
max_weight = np.max(weights)
print("Min Height:", min_height, "Max Height:", max_height)
print("Min Weight:", min_weight, "Max Weight:", max_weight)

Min Height: 150 Max Height: 190
Min Weight: 50 Max Weight: 90


In [19]:
import numpy as np
houses = np.array([
                    [3, 2000, 10],
                    [2, 1500, 20],
                    [4, 2500, 5],
                    ])

In [20]:
updated_bedrooms = houses[:, 0] + 1  #  1-ci  sutuna + 1 
print("Updated bedrooms after broadcasting:\n", updated_bedrooms)

Updated bedrooms after broadcasting:
 [4 3 5]


In [21]:
updated_age = houses[:, 2] - 5  #  3-cu sutundan - 5
print("Updated house ages after broadcasting:\n", updated_age)

Updated house ages after broadcasting:
 [ 5 15  0]


In [22]:
adjusted_size = houses[:, 1] * 1.1
print("Adjusted house sizes (sq ft) by 10% increase:\n", adjusted_size)

Adjusted house sizes (sq ft) by 10% increase:
 [2200. 1650. 2750.]


--------------------------------------------------------------

In [23]:
print(houses.shape)


(3, 3)


In [24]:
reshaped_houses = houses.reshape(-1)   #  (9,0)
print("Reshaped houses (flattened):\n", reshaped_houses)

Reshaped houses (flattened):
 [   3 2000   10    2 1500   20    4 2500    5]


In [25]:
reshaped_houses_1x9 = houses.reshape(1, 9)  # (1,9)
print("Reshaped houses into 1x9:\n", reshaped_houses_1x9.shape)

Reshaped houses into 1x9:
 (1, 9)


---------------------------------------

In [26]:

more_houses = np.array([[5,
                         3000,
                         15]])

In [27]:
joined_houses = np.concatenate((houses,more_houses),
                               axis=0) # alt alta birlesdirir
print("Joined houses (by rows):\n", joined_houses)

Joined houses (by rows):
 [[   3 2000   10]
 [   2 1500   20]
 [   4 2500    5]
 [   5 3000   15]]


In [28]:
extra_data = np.array([[100000],
                       [120000],
                       [140000]])

joined_columns = np.concatenate((houses, extra_data),
                                 axis=1)  # yan-yana birlesdirir
print("Joined houses with extra column (price):\n", joined_columns)

Joined houses with extra column (price):
 [[     3   2000     10 100000]
 [     2   1500     20 120000]
 [     4   2500      5 140000]]


In [29]:
stacked_houses_vertically = np.vstack((houses, more_houses))    #  alt-alta birlesdirir
print("Vertically stacked houses:\n", stacked_houses_vertically)

Vertically stacked houses:
 [[   3 2000   10]
 [   2 1500   20]
 [   4 2500    5]
 [   5 3000   15]]


In [30]:
stacked_houses_horizontally = np.hstack((houses, extra_data))   #  yan-yana  birledirir
print("Horizontally stacked houses with extra column:\n", stacked_houses_horizontally)

Horizontally stacked houses with extra column:
 [[     3   2000     10 100000]
 [     2   1500     20 120000]
 [     4   2500      5 140000]]


-----------------------------------------------------------------------------

In [31]:
houses

array([[   3, 2000,   10],
       [   2, 1500,   20],
       [   4, 2500,    5]])

In [32]:
weights = np.array([50, 100,-20])
bias = 30000
predicted_prices = np.dot(houses, weights) + bias
print("Predicted prices:", predicted_prices)

Predicted prices: [229950 179700 280100]


In [33]:
house_norms = np.linalg.norm(houses, axis=1, keepdims=True)  # ||x|| = sqrt( bedrooms^2 +  size^2 + age^2)
normalized_houses = houses / house_norms   # x / ||x||

predicted_prices_normalized = np.dot(normalized_houses, weights) + bias
print("Predicted prices (normalized):", predicted_prices_normalized)

Predicted prices (normalized): [30099.97363787 30099.79104138 30100.03967187]


## Singular value decomposition


In [36]:
houses

array([[   3, 2000,   10],
       [   2, 1500,   20],
       [   4, 2500,    5]])

In [35]:
U, S, Vt = np.linalg.svd(houses, full_matrices=False)

print("U matrix:\n", U,'\n')
print("Singular values:\n", S,'\n')
print("V transpose matrix:\n", Vt,'\n')

U matrix:
 [[-5.65685408e-01 -5.29730785e-05 -8.24621135e-01]
 [-4.24281626e-01 -8.57461456e-01  2.91109864e-01]
 [-7.07096261e-01  5.14548198e-01  4.85030958e-01]] 

Singular values:
 [3.53558218e+03 1.45812349e+01 4.84936379e-02] 

V transpose matrix:
 [[-0.00151998 -0.99998634 -0.00500002]
 [ 0.02353099  0.00496287 -0.99971079]
 [ 0.99972195 -0.00163719  0.02352313]] 



Covariance


In [ ]:
cov_matrix = np.cov(houses, rowvar=False)
print("Covariance matrix:\n", cov_matrix)

Correlation matrix


In [ ]:
corr_matrix = np.corrcoef(houses, rowvar=False)
print("Pearson correlation matrix:\n", corr_matrix)